In [1]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

# Label Encoder
LabelEncoder change the labels into number. 
e.g: 
> [1, 2, 2, 3] ==> [0, 1, 1, 2]

> ['Tom', 'John', 'Mike', 'John'] == > [1, 2, 3, 2]

In [29]:
le = LabelEncoder()
le.fit(['US', 'GB', 'CH'])
nationality = le.transform(['US', 'US','CH', 'GB', 'CH'])
print(nationality)

le.fit(['PROGRAMMER', 'DRIVER', 'COOK', 'STUDENT', 'TEACHER', 'COOK'])
professor = le.transform(['DRIVER', 'COOK', 'STUDENT', 'COOK', 'PROGRAMMER'])
print(professor)

[2 2 0 1 0]
[1 0 3 0 2]


In [ ]:
enc = OneHotEncoder()

In [31]:
enc.fit([nationality, professor])

OneHotEncoder(categorical_features='all', dtype=<type 'float'>,
       handle_unknown='error', n_values='auto', sparse=True)

In [33]:
enc.fit([[2,1],[2,0],[0,3],[1,0],[0,2]])

OneHotEncoder(categorical_features='all', dtype=<type 'float'>,
       handle_unknown='error', n_values='auto', sparse=True)

In [38]:
print enc.active_features_
print enc.n_values_

[0 1 2 3 4 5 6]
[3 4]


# n\_values\_ 
### n_values is the array of shape(n_features)
Maximun number of values per feature. 
The first **3** is the max number of nationality. Means there are 3 nation in this feature. 
The second **4** is the max number of professor number. Means we input 4 different professor. 

In [43]:
enc.transform([[2,1]]).toarray()

array([[ 0.,  0.,  1.,  0.,  1.,  0.,  0.]])

In [45]:
enc.transform([[2,0], [2, 1]]).toarray()

array([[ 0.,  0.,  1.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  1.,  0.,  0.]])

### Change [2, 0] to [0, 0, 1, 1, 0, 0, 0]

# Feature and Label
feature contains different label. 

LanbelEncoder() change label to number

OneHotEncoder() change number to a more *scitifical* number.

# An example of the using of LableEncoder and OneHotEncoder

In [ ]:
# In this exercise we'll load the titanic data (from Project 0)
# And then perform one-hot encoding on the feature names

import numpy as np
import pandas as pd

# Load the dataset
X = pd.read_csv('titanic_data.csv')
# Limit to categorical data
X = X.select_dtypes(include=[object])

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

# TODO: Create a LabelEncoder object, which will turn all labels present in
#       in each feature to numbers. For example, the labels ['cat', 'dog', 'fish']
#       might be transformed into [0, 1, 2]

le = LabelEncoder()

# TODO: For each feature in X, apply the LabelEncoder's fit_transform
#       function, which will first learn the labels for the feature (fit)
#       and then change the labels to numbers (transform). 

for feature in X:
      X[feature] = le.fit_transform(X[feature])
      # features = X[feature]
      # le.fit(features)
      # X[feature] = le.transform(features)

# TODO: Create a OneHotEncoder object, which will create a feature for each
#       label present in the data. For example, for a feature 'animal' that had
#       the labels ['cat','dog','fish'], the new features (instead of 'animal') 
#       could be ['animal_cat', 'animal_dog', 'animal_fish']

ohe = OneHotEncoder()

# TODO: Apply the OneHotEncoder's fit_transform function to all of X, which will
#       first learn of all the (now numerical) labels in the data (fit), and then
#       change the data to one-hot encoded entries (transform).

onehotlabels = ohe.fit_transform(X)